/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.org.ultrainstinct.ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import com.org.ultrainstinct.dao.AuthDAO;
import com.org.ultrainstinct.dao.impl.AuthDAOImpl;
import com.org.ultrainstinct.main.Main;
import com.org.ultrainstinct.utils.EmailSender;
import com.org.ultrainstinct.utils.MessageDialog;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author Minh Ngoc
 */
public class DangNhapJDialog extends javax.swing.JDialog {

    private AuthDAO authDao = new AuthDAOImpl();
    private String currentOTP;
    /**
     * Creates new form DangNhapJDialog
     */
    public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    DangNhapJDialog() {
        
    }

//    public DangNhapJDialog() {
//        initComponents();
//        setLocationRelativeTo(null);
//        init();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttenDangNhap = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        txtmatKhau = new javax.swing.JPasswordField();
        btnForgot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("ĐĂNG NHẬP");

        txttenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttenDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txttenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenDangNhapActionPerformed(evt);
            }
        });

        btnDangNhap.setBackground(new java.awt.Color(0, 153, 0));
        btnDangNhap.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnForgot.setForeground(new java.awt.Color(0, 102, 255));
        btnForgot.setText("Quên mật khẩu");
        btnForgot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(txtmatKhau)
                            .addComponent(txttenDangNhap)
                            .addComponent(btnForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(txttenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtmatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(848, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String username = txttenDangNhap.getText();
         String password = new String(txtmatKhau.getPassword());
        try {
            if (authDao.logIn(username, password)) {
                MessageDialog.alert(this, "Login successfully");
                SwingUtilities.invokeLater(() -> {
                    Main main = new Main();
                    main.setVisible(true);
                });
                // Optionally, close the login dialog if needed
                this.dispose();
            } else {
                MessageDialog.alert(this, "Invalid username or password");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DangNhapJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txttenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenDangNhapActionPerformed

    private void btnForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotActionPerformed
        // TODO add your handling code here:
        String username = txttenDangNhap.getText();
        new ForgotPasswordWorker(username).execute();
    }//GEN-LAST:event_btnForgotActionPerformed
    private class ForgotPasswordWorker extends SwingWorker<Void, Void> {
        private String username;

        public ForgotPasswordWorker(String username) {
            this.username = username;
        }

        @Override
        protected Void doInBackground() throws Exception {
            try {
                String email = authDao.getEmailByUsername(username);
                if (email != null) {
                    currentOTP = generateOTP();
                    EmailSender.sendOtpToUser(email, currentOTP);
                } else {
                    JOptionPane.showMessageDialog(DangNhapJDialog.this, "Username does not exist.", "Notification", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(DangNhapJDialog.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(DangNhapJDialog.this, "Error retrieving email.", "Notification", JOptionPane.ERROR_MESSAGE);
            }
            return null;
        }

        @Override
        protected void done() {
            try {
                get();
                String enteredOTP = JOptionPane.showInputDialog(DangNhapJDialog.this, "Enter the OTP sent to your email:", "OTP Verification", JOptionPane.INFORMATION_MESSAGE);
                if (enteredOTP != null && enteredOTP.equals(currentOTP)) {
                    String newPassword = JOptionPane.showInputDialog(DangNhapJDialog.this, "Enter your new password:", "Reset Password", JOptionPane.INFORMATION_MESSAGE);
                    if (newPassword != null && !newPassword.trim().isEmpty()) {
                        authDao.updatePassword(username, newPassword);
                        JOptionPane.showMessageDialog(DangNhapJDialog.this, "Password has been reset successfully.", "Notification", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(DangNhapJDialog.this, "Password cannot be empty.", "Notification", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(DangNhapJDialog.this, "Invalid OTP.", "Notification", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(DangNhapJDialog.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(DangNhapJDialog.this, "Error during OTP verification.", "Notification", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private String generateOTP() {
        Random random = new Random();
        int otp = 100000 + random.nextInt(900000);  // Generate a random 6-digit number
        return String.valueOf(otp);
    }
    
    void init() {

        // Đặt tiêu đề cho JDialog
        this.setTitle("Full Screen Image Dialog");

        // Lấy kích thước màn hình
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Đặt kích thước JDialog bằng kích thước màn hình
        this.setSize(1450, screenSize.height);

        // Đặt vị trí JDialog ở góc trên bên trái màn hình (0,0)
        setLocationRelativeTo(null);

        // Đặt JDialog luôn ở trên cùng (tùy chọn)
        this.setAlwaysOnTop(true);

        // Tạo một JLabel để chứa hình ảnh
        JLabel imageLabel = new JLabel();

        // Đọc hình ảnh từ file
        ImageIcon imageIcon = new ImageIcon(".//src//com//org//ultrainstinct//icon/img.png");
        // Đặt hình ảnh vào JLabel
        imageLabel.setIcon(imageIcon);

        // Đặt layout cho JDialog
        this.setLayout(new BorderLayout());

        // Thêm JLabel vào JDialog
        this.add(imageLabel, BorderLayout.CENTER);
        // Tạo các thành phần

        // Hiển thị JDialog
//        this.setVisible(true);
    }

    /**
     * s
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                DangNhapJDialog dialog = new DangNhapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnForgot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtmatKhau;
    private javax.swing.JTextField txttenDangNhap;
    // End of variables declaration//GEN-END:variables

}
